apiVersion: v1
kind: Secret
metadata:
  name: {{ meteringconfig_spec.tls.secretName }}
  labels:
    app: metering
type: Opaque
data:
  ca.crt: "{{ meteringconfig_spec.tls.certificate | b64encode }}"
  ca.key: "{{ meteringconfig_spec.tls.key | b64encode }}"
