apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-metering

bases:
  - ../../operator
  - ../../olm

# Changes:
# containerImage
# name of csv
# capabilities
# url
# base64data
# metering deployment images

resources:
  - namespace.yaml
