apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ .Values.olm.catalogSourceName }}
  namespace: {{ .Values.olm.catalogSourceNamespace }}
spec:
  configMap: {{ .Values.olm.catalogSourceConfigMapName }}
  sourceType: internal
  publisher: metering
  displayName: Metering Operator Testing
