{% if meteringconfig_spec.hadoop.spec.config.s3Compatible.ca.createSecret %}
apiVersion: v1
kind: Secret
metadata:
  name: hadoop-s3-compatible-ca
  labels:
    app: hadoop
type: Opaque
data:
  ca-bundle.crt: "{{ meteringconfig_spec.hadoop.spec.config.s3Compatible.ca.content | b64encode }}"
{% endif %}
