{% if meteringconfig_spec.hadoop.spec.config.azure.createSecret %}
apiVersion: v1
kind: Secret
metadata:
  name: hadoop-azure-credentials
data:
{% if meteringconfig_spec.hadoop.spec.config.azure.storageAccountName %}
  azure-storage-account-name: "{{ meteringconfig_spec.hadoop.spec.config.azure.storageAccountName | b64encode }}"
{% endif %}
{% if meteringconfig_spec.hadoop.spec.config.azure.secretAccessKey %}
  azure-secret-access-key: "{{ meteringconfig_spec.hadoop.spec.config.azure.secretAccessKey | b64encode }}"
{% endif %}
{% endif %}
