{% if meteringconfig_spec.hadoop.spec.config.aws.createSecret %}
apiVersion: v1
kind: Secret
metadata:
  name: hadoop-aws-credentials
data:
{% if meteringconfig_spec.hadoop.spec.config.aws.accessKeyID %}
  aws-access-key-id: "{{ meteringconfig_spec.hadoop.spec.config.aws.accessKeyID | b64encode }}"
{% endif %}
{% if meteringconfig_spec.hadoop.spec.config.aws.secretAccessKey %}
  aws-secret-access-key: "{{ meteringconfig_spec.hadoop.spec.config.aws.secretAccessKey | b64encode }}"
{% endif %}
{% endif %}
