{% if meteringconfig_spec.hadoop.spec.config.gcs.createSecret %}
apiVersion: v1
kind: Secret
metadata:
  name: hadoop-gcs-credentials
data:
  gcs-service-account.json: "{{ meteringconfig_spec.hadoop.spec.config.gcs.serviceAccountKeyJSON | toJson | b64encode }}"
{% endif %}
