{% if meteringconfig_spec.hadoop.spec.config.s3Compatible.createSecret %}
apiVersion: v1
kind: Secret
metadata:
  name: hadoop-s3-compatible-credentials
data:
{% if meteringconfig_spec.hadoop.spec.config.s3Compatible.accessKeyID %}
  aws-access-key-id: "{{ meteringconfig_spec.hadoop.spec.config.s3Compatible.accessKeyID | b64encode }}"
{% endif %}
{% if meteringconfig_spec.hadoop.spec.config.s3Compatible.secretAccessKey %}
  aws-secret-access-key: "{{ meteringconfig_spec.hadoop.spec.config.s3Compatible.secretAccessKey | b64encode }}"
{% endif %}
{% endif %}
