apiVersion: v1
kind: ServiceAccount
metadata:
  name: hdfs
  labels:
    app: hdfs
{% if .Values.hadoop.spec.hdfs.namenode.annotations %}
  annotations: {{ meteringconfig_spec.hadoop.spec.hdfs.namenode.annotations }}
{% endif %}
