{{- if .Values.hadoop.spec.config.gcs.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: hadoop-gcs-credentials
data:
  gcs-service-account.json: {{ .Values.hadoop.spec.config.gcs.serviceAccountKeyJSON | toJson | b64enc | quote }}
{{- end -}}
